# <center><span style="color:#8E24AA;">📚 CountVectorizer()</span></center>

---

## 📖 Definition

**CountVectorizer()** is a **Scikit-learn** class used to convert a collection of text documents into a **Bag of Words (BoW) matrix** by counting the frequency of each word.

> **Simple Definition:** CountVectorizer converts text into numerical vectors by counting how many times each word appears in a document.

---

## 📦 Import

```python
from sklearn.feature_extraction.text import CountVectorizer

# Create CountVectorizer Object
cv = CountVectorizer()
```

---

## 🎯 Technique Used

- **Bag of Words (BoW)**
- **N-Grams** (using `ngram_range` parameter)

---

## ⚙️ Internal Working of CountVectorizer()

```text
Input Documents
       │
       ▼
Convert Text to Lowercase
       │
       ▼
Tokenization
       │
       ▼
Remove Stopwords (Optional)
       │
       ▼
Apply N-Grams (Optional)
       │
       ▼
Create Vocabulary
       │
       ▼
Assign Index to Each Word
       │
       ▼
Count Word Frequency
       │
       ▼
Create Sparse Matrix
       │
       ▼
Bag of Words (BoW) Matrix
```


## ⭐ Interview Questions

### Q1. What is CountVectorizer?

**Answer:**
CountVectorizer is a Scikit-learn class that converts text into a Bag of Words matrix by counting word frequencies.

---

### Q2. Which library provides CountVectorizer?

**Answer:**

```python
from sklearn.feature_extraction.text import CountVectorizer
```

---

### Q3. Which feature extraction technique uses CountVectorizer?

**Answer:**

- Bag of Words (BoW)
- N-Grams

---

### Q4. What is the output of CountVectorizer?

**Answer:**
A **sparse matrix** containing word frequency counts.

---

## ⭐ One-Line Interview Answer

**CountVectorizer()** is a **Scikit-learn** class that implements the **Bag of Words (BoW)** technique by converting text into a sparse matrix of word frequency counts.

# <center><span style="color:#8E24AA;">📚 CountVectorizer() Parameters</span></center>

```python
CountVectorizer(

 input='content',

    encoding='utf-8',

    decode_error='strict',

    strip_accents=None,

    lowercase=True,

    preprocessor=None,

    tokenizer=None,

    stop_words=None,

    token_pattern=r'(?u)\b\w\w+\b',

    ngram_range=(1,1),

    analyzer='word',

    max_df=1.0,

    min_df=1,

    max_features=None,

    vocabulary=None,

    binary=False,

    dtype=np.int64

)
```



## Most Important Parameters

| Parameter | Description | Example |
|-----------|-------------|---------|
| `stop_words` | Removes common stopwords | `stop_words='english'` |
| `lowercase` | Converts text to lowercase | `lowercase=True` |
| `max_features` | Keeps only the top N frequent words | `max_features=100` |
| `min_df` | Ignores words appearing in fewer than N documents | `min_df=2` |
| `max_df` | Ignores words appearing in more than a specified number/percentage of documents | `max_df=0.8` |
| `binary` | Uses 0/1 instead of word frequency | `binary=True` |
| `ngram_range` | Creates Unigrams, Bigrams, Trigrams | `ngram_range=(1,2)` |
| `token_pattern` | Regex pattern used for tokenization | `token_pattern=r'(?u)\b\w+\b'` |
| `analyzer` | Type of features to extract | `'word'`, `'char'`, `'char_wb'` |
| `vocabulary` | Uses a custom vocabulary | `vocabulary=['python','nlp']` |
| `dtype` | Data type of the output matrix | `dtype=int` |
| `encoding` | Text encoding | `encoding='utf-8'` |
| `decode_error` | Action when decoding fails | `'ignore'` |
| `strip_accents` | Removes accents from characters | `'ascii'` or `'unicode'` |
| `preprocessor` | Custom preprocessing function | `preprocessor=my_func` |
| `tokenizer` | Custom tokenizer function | `tokenizer=my_tokenizer` |

---


In [2]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

print(dir(cv))

['_CountVectorizer__metadata_request__fit', '_CountVectorizer__metadata_request__transform', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_tags__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_build_request_for_signature', '_char_ngrams', '_char_wb_ngrams', '_check_stop_words_consistency', '_check_vocabulary', '_count_vocab', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_get_default_requests', '_get_doc_link', '_get_metadata_request', '_get_param_names', '_get_params_html', '_html_repr', '_limit_features', '_parameter_constraints', '_repr_html_', '_repr_html_inner', '_repr_mimebun

In [5]:
documents = [
    "I love NLP",
    "I love Python",
    "Python is useful for NLP"
]

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample Documents
documents = [
    "I love NLP",
    "I love Python",
    "Python is useful for NLP"
]

# Create CountVectorizer Object
cv = CountVectorizer()

# Learn Vocabulary
cv.fit(documents)
print("Vocabulary Learned Successfully")




Vocabulary Learned Successfully


In [10]:


# Convert Documents into Bag of Words Matrix
bow = cv.transform(documents)
print("\nBag of Words Matrix:")
print(bow.toarray())




Bag of Words Matrix:
[[0 0 1 1 0 0]
 [0 0 1 0 1 0]
 [1 1 0 1 1 1]]


In [11]:
# Learn Vocabulary + Convert Documents
bow = cv.fit_transform(documents)
print("\nfit_transform() Output:")
print(bow.toarray())




fit_transform() Output:
[[0 0 1 1 0 0]
 [0 0 1 0 1 0]
 [1 1 0 1 1 1]]


In [12]:
# Display Vocabulary
print("\nFeature Names:")
print(cv.get_feature_names_out())




Feature Names:
['for' 'is' 'love' 'nlp' 'python' 'useful']


In [13]:
# Display Vocabulary Dictionary
print("\nVocabulary Dictionary:")
print(cv.vocabulary_)





Vocabulary Dictionary:
{'love': 2, 'nlp': 3, 'python': 4, 'is': 1, 'useful': 5, 'for': 0}


In [14]:
# Convert Matrix Back to Words
print("\nInverse Transform:")
print(cv.inverse_transform(bow))





Inverse Transform:
[array(['love', 'nlp'], dtype='<U6'), array(['love', 'python'], dtype='<U6'), array(['nlp', 'python', 'is', 'useful', 'for'], dtype='<U6')]


In [15]:
# Display All Parameters
print("\nParameters:")
print(cv.get_params())





Parameters:
{'analyzer': 'word', 'binary': False, 'decode_error': 'strict', 'dtype': <class 'numpy.int64'>, 'encoding': 'utf-8', 'input': 'content', 'lowercase': True, 'max_df': 1.0, 'max_features': None, 'min_df': 1, 'ngram_range': (1, 1), 'preprocessor': None, 'stop_words': None, 'strip_accents': None, 'token_pattern': '(?u)\\b\\w\\w+\\b', 'tokenizer': None, 'vocabulary': None}


In [16]:
# Change Parameter Values
cv.set_params(stop_words='english')
print("\nUpdated CountVectorizer:")
print(cv)


Updated CountVectorizer:
CountVectorizer(stop_words='english')


---
# <center>✨ The End ✨</center>
---